### ISSUE TITLE
Revamp the Counting Sort implementation

### ISSUE THREAD

**Issue by alexfertel** [alexfertel/rust-algorithms#12]
The current implementation of [Counting Sort](./src/sorting/counting_sort.rs) supports sorting integers only, but it can be extended to support any form of object that is represented by an integer key.

Also, the current implementation is missing tests for stability. Since `radix sort` relies on this algorithms' property of being stable, it would be nice to assert that it is present.

* Extend Counting Sort to the general case of having objects with integer keys.
* Add tests that assert the stability of the algorithm.

**Comment by agrism** [comment]
> any form of object that is represented by an integer key

@alexfertel do you mean struct tuples? For example: `struct My(usize, usize)`

**Comment by alexfertel** [comment]
@agrism Sorry, I was unclear. What I meant was something like a `trait` that captured the notion of having an integer key. For example:

```rust
trait Keyed {
    fn key(&self) -> usize;
}
```

And then we use `Keyed` like so:

```rust
pub fn counting_sort<T: Keyed + Ord>(array: &[T]) -> Vec<T> { ... }
```

Hopefully, that makes sense to you.
